namespace: abikouo
name: gha_actions
version: 0.1.0
readme: README.md
authors:
  - abikouo (@abikouo)
description: test collection
license_file: COPYING
tags: [amazon, aws, cloud]
repository: https://github.com/abikouo/gha_testing
