authors:
  - abikouo (https://github.com/abikouo)
description: Collection to test Ansible cloud Github actions.
documentation: ''
homepage: ''
issues: https://github.com/abikouo/gha_testing/issues
license_file: ''
namespace: abikouo
name: gha_testing
readme: ''
repository: https://github.com/abikouo/gha_testing
tags:
  - CI
  - github
  - actions
version: 1.0.2
build_ignore:
  - '*.tar.gz'
