name: Prepare ansible release
description: |
  Run repository tox environment prepare_release if it exists or 
  create a default one and run it.

inputs:
  path:
    description: The path to the collection being released.
    required: true
  version:
    description: The release version.
    required: true

runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install python required libraries
      run: pip install -U tox antsibull-changelog
      shell: bash

    - name: Run tox environment prepare_release
      id: tox_prepare_release
      continue-on-error: true
      run: tox -e prepare_release -vv
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        RELEASE_VERSION: ${{ inputs.version }}
