---
name: Labeller

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The repository name
        required: true
        type: string
      id:
        description: The pull request identifier
        required: true
        type: number
      name:
        description: The label to add to the pull request
        required: true
        type: string

jobs:
  approve:
    permissions:
      contents: write
      pull-requests: write
    env:
      source: "./checkout_path"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: ${{ inputs.source }}

      - name: add label to the pull request
        run: gh pr edit ${{ inputs.id }} --add-label "${{ inputs.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: ${{ inputs.source }}
