name: ansible-lint
on:
  workflow_dispatch:
    inputs:
      pull_request_url:
        description: The url of the pull request to test
        required: true

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: abikouo/gha_testing/.github/actions/checkout_ref@main
        with:
          url: ${{ inputs.pull_request_url }}

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main