---
name: ansible-lint

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The repository name
        required: true
      ref:
        description: The ref to checkout
        required: true

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.repository }}

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.16.0