name: ansible_bot
on:
  workflow_call:
  # issues:
  #   types:
  #     - opened
  #     - reopened
  #     - edited
  # pull_request_review:
  #   types:
  #     - submitted
  #     - edited
  #     - dismissed
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  #     - reopened
  #     - synchronize

jobs:
  labelling:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install required libraries
        run: |
          pip install pygithub
        shell: bash

      - name: Download script
        run: curl -o add_labels.py https://raw.githubusercontent.com/abikouo/gha_testing/main/scripts/add_labels.py
        shell: bash

      - name: add issue/pull request labels
        run: python ./add_labels.py
        env:
          GH_EVENT_NUMBER: ${{ github.event.issue.number }}
          GH_REPOSITORY: ${{ github.repository }}
          GH_EVENT_ACTION: ${{ github.event.action }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
