name: AzureRM
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

jobs:
  credentials:
    runs-on: ubuntu-latest
    env:
      source: "./source"
      ansible_version: "milestone"
      python_version: "3.11"
    strategy:
      fail-fast: false
    name: "Generate azure credentials"
    steps:
      - name: Create AzureRM session credentials
        uses: abikouo/github_actions/.github/actions/ansible_azure_test_provider@ansible_test_providers_20240119
        with:
          collection_path: "."
          ansible_core_ci_key: "${{ secrets.ANSIBLE_CORE_CI_KEY }}"