name: black
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_call:
  # better to be called with
  # pull_request:
  #   types:
  #     - labeled

jobs:
  format:
    if: "contains(github.event.pull_request.labels.*.name, 'black-format-code')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'checkout fork repository on ${{ github.head_ref }}'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: "0"

      - name: Check black formatting
        id: black_check
        continue-on-error: true
        run: |
          tox -e black -vv 2>/tmp/black_check.txt
        shell: bash

      - name: Run black formatting
        run: |
          tox -e black_format -vv -- $(grep "would reformat" /tmp/black_check.txt | cut -d ' ' -f3 | tr '\n' ' ')
        shell: bash
        if: steps.black_check.outcome != 'success'

      - name: (debug only) list files in diff
        run: |
          git status
        shell: bash
        if: steps.black_check.outcome != 'success'

      - name: commit and push changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated changes for black formatting"