name: changelog
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_call:
  # expected to be called with
  # pull_request:
  #   types:
  #     - labeled

jobs:
  create:
    if: "contains(github.event.pull_request.labels.*.name, 'create-changelog')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'checkout fork repository on ${{ github.head_ref }}'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: "0"

      - name: Set up Python '3.9'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          pip install -U pyyaml pygithub tox
        shell: bash

      - name: Download script
        run: >-
          curl -o /tmp/add_changelog.py
          https://raw.githubusercontent.com/abikouo/gha_testing/main/scripts/add_changelog.py

      - name: Validate or add pull request changelog
        run:
          python3 /tmp/add_changelog.py
        env:
          PR_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: (debug only) list files in diff
        run: |
          git status
        shell: bash
        if: steps.black_check.outcome != 'success'

      - name: commit and push changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated changes for changelog fragment"
          file_pattern: changelogs/fragments/*.yaml