---
name: integration-cloud-aws_ops

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch to test
        required: false
        default: main
      ansible_test_targets:
        description: The target to test
        required: false
        default: ""


jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      source: "./source"
      python_version: "3.9"
      ansible_version: "stable-2.14"
    steps:
      - name: Checkout collection
        uses: actions/checkout@v3
        with:
          repository: redhat-cop/cloud.aws_ops
          path: ${{ env.source }}
          ref: ${{ inputs.ref }}

      - name: Build and install collection
        id: install
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          install_python_dependencies: false
          source_path: ${{ env.source }}

      - name: Create AWS/sts session credentials
        uses: ansible-network/github_actions/.github/actions/ansible_aws_test_provider@main
        with:
          collection_path: ${{ steps.install.outputs.collection_path }}
          ansible_core_ci_key: ${{ secrets.ANSIBLE_CORE_CI_KEY }}

      # we use raw git to create a repository in the tests
      # this fails if the committer doesn't have a name and an email set
      - name: Set up git
        run: |
          git config --global user.email gha@localhost
          git config --global user.name "Github Actions"
        shell: bash

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@main
        with:
          collection_path: ${{ steps.install.outputs.collection_path }}
          python_version: ${{ env.python_version }}
          ansible_version: ${{ env.ansible_version }}
          ansible_test_requirement_files: 'test-requirements.txt'
          ansible_test_targets: ${{ inputs.ansible_test_targets }}