---
name: Code Review
concurrency:
  group: pull-request-size-${{ github.head_ref }}
  cancel-in-progress: true
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

jobs:
  pull-request-size:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/pull-request-size.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}