---
name: Create

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The name of the tag to create
        required: true
        type: string
      branch_name:
        description: The branch name to create tag from.
        required: true
        type: string

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.GH_TOKEN }}

      - name: create and push git tag
        run: |
          git tag ${{ inputs.tag_name }}
          git push origin ${{ inputs.tag_name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: "${{ github.repository }} ${{ github.ref }}"
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false