---
name: Dispatch

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The release tag to create.
        required: true
      branch:
        description: The release branch to create tag from.
        required: false
        default: main

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2