name: Integration kubernetes.core
on:
  workflow_dispatch:
    inputs:
      repository:
        description: The repository
        default: abikouo/kubernetes.core
        type: string
      branch:
        description: The branch to checkout
        type: string
      test_targets:
        description: the list of targets to test
        type: string
        required: true

jobs:
  splitter:
    runs-on: ubuntu-latest
    outputs:
      ansible_test_targets: ${{ steps.split.outputs.ansible_test_targets }}
      all_jobs: ${{ steps.split.outputs.all_jobs }}
    steps:
      - name: Read target
        id: split
        run: |
          import json, os
          result = {x+1: v for x, v in enumerate(os.environ.get("ALL_TARGETS").split(","))}
          all_jobs = list(result.keys())
          with open(os.environ.get('GITHUB_OUTPUT'), "a", encoding="utf-8") as fh:
              fh.write(f"ansible_test_targets={json.dumps(result)}\n")
              fh.write(f"all_jobs={json.dumps(all_jobs)}\n")
        shell: python
        env:
          ALL_TARGETS: ${{ inputs.test_targets }}
  integration:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    needs:
      - splitter
    if: ${{ needs.splitter.outputs.ansible_test_targets != '' }}
    env:
      source: "./source"
      cloud_common: "./cloudcommon"
      ansible_posix: "./ansible_posix"
      community_general: "./community_general"
      python_version: '3.12'
    strategy:
      fail-fast: false
      matrix:
        enable-turbo-mode:
          - true
          - false
        workflow-id: ${{ fromJson(needs.splitter.outputs.all_jobs) }}
    name: "integration-fallible-${{ matrix.workflow-id }}-enable_turbo=${{ matrix.enable-turbo-mode }}"
    steps:
      - name: Select target to run
        id: targets
        run: |
          import json, os
          with open(os.environ.get('GITHUB_OUTPUT'), "a", encoding="utf-8") as fh:
              fh.write(f'ansible_test_targets={json.loads(os.environ.get("ALL_TEST_TARGETS")).get(os.environ.get("WORKFLOW_ID"))}\n')
        shell: python
        env:
          ALL_TEST_TARGETS: ${{ needs.splitter.outputs.ansible_test_targets }}
          WORKFLOW_ID: ${{ matrix.workflow-id }}

      - name: Display ansible test targets
        run: |
          echo "ansible_test_targets -> ${{ steps.targets.outputs.ansible_test_targets }}"

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.python_version }}'
    
      - name: Install virtualenv
        run: |
          sudo apt-get update
          sudo apt-get install python3-virtualenv
        shell: bash

      - name: Create virtualenv
        run: |
          virtualenv --no-site-packages --python 3.12 /home/runner/collections/env
          source /home/runner/collections/env/bin/activate
          ansible-test --version
        shell: bash

      # - name: Checkout kubernetes.core repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ${{ inputs.repository }}
      #     path: ${{ env.source }}
      #     ref: ${{ inputs.branch }}

      # - name: Build virtual environment
      #   run: |
      #     python3 -m pip uninstall ansible-core
      #     ansible-test --version
      #   shell: bash
      #   working-directory: ${{ env.source }}

      # - name: Set up Python ${{ env.python_version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '${{ env.python_version }}'

      # - name: Install fallible (ansible)
      #   run: pip3 install --upgrade 'fallible[compat]'
      #   shell: bash

      # - name: identify collection
      #   id: identify
      #   uses: ansible-network/github_actions/.github/actions/identify_collection@main
      #   with:
      #     source_path: ${{ env.source }}

      # - name: Build collection
      #   run: ansible-galaxy collection build -vvv
      #   shell: bash
      #   working-directory: ${{ env.source }}

      # - name: Install collection and dependencies (with --pre flag)
      #   run: ansible-galaxy collection install ./${{ steps.identify.outputs.tar_file }} --pre -p /home/runner/collections
      #   shell: bash
      #   working-directory: ${{ env.source }}

      # - name: Disable selinux with selinux_please_lie_to_me
      #   run: |
      #     python3 -m pip install wheel --upgrade
      #     python3 -m pip uninstall -y selinux
      #     python3 -m pip install selinux_please_lie_to_me
      #     python3 -m pip install -r requirements.txt -r test-requirements.txt
      #   shell: bash
      #   working-directory: ${{ env.source }}

      # - name: create kubernetes cluster
      #   uses: helm/kind-action@v1.8.0
      #   with:
      #     node_image: "kindest/node:v1.29.2"

      # # Install collection dependencies
      # - name: Install collections dependencies
      #   run: |
      #     ansible-galaxy collection install cloud.common
      #     ansible-galaxy collection install ansible.posix
      #     ansible-galaxy collection install community.general
      #   shell: bash

      # - name: Ensure ansible-test version
      #   run: ansible-test --version
      #   shell: bash

      # - name: Run integration tests
      #   run: >-
      #     ansible-test integration
      #     --diff
      #     --no-temp-workdir
      #     --color
      #     --skip-tags False
      #     --python 3.12
      #     ${{ steps.targets.outputs.ansible_test_targets }}
      #     -v
      #   shell: bash
      #   working-directory: /home/runner/collections/ansible_collections/kubernetes/core
      #   env:
      #     ENABLE_TURBO_MODE: ${{ matrix.enable-turbo-mode }}
