name: Integration
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      source: "./source"
      amazon_dir: "./amazon_aws"
    steps:
      - name: Checkout collection
        uses: actions/checkout@v3
        with:
          path: ${{ env.source }}

      - name: Build and install collection
        id: install-collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          source_path: ${{ env.source }}

      # checkout and install 'amazon.aws'
      - name: checkout ansible-collections/amazon.aws
        uses: ansible-network/github_actions/.github/actions/checkout_dependency@main
        with:
          repository: ansible-collections/amazon.aws
          path: ${{ env.amazon_dir }}
          ref: main

      - name: install amazon.aws collection
        uses: ansible-network/github_actions/.github/actions/build_install_collection@main
        with:
          install_python_dependencies: true
          source_path: ${{ env.amazon_dir }}

      - name: Create AWS session credentials
        run: echo '${{ secrets.ANSIBLE_CORE_CI_KEY }}' > ~/.ansible-core-ci.key
        shell: bash

      # we use raw git to create a repository in the tests
      # this fails if the committer doesn't have a name and an email set
      - name: Set up git
        run: |
          git config --global user.email gha@localhost
          git config --global user.name "Github Actions"
        shell: bash

      - name: Run integration tests
        uses: ansible-network/github_actions/.github/actions/ansible_test_integration@main
        with:
          collection_path: ${{ steps.install-collection.outputs.collection_path }}
          python_version: '3.9'
          ansible_version: stable-2.14
          ansible_test_requirement_files: ''
