name: Integration
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  format:
    if: "contains(github.event.pull_request.labels.*.name, 'do-not-test')"
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: display collection version
        run: |
          cat plugins/module.py
        shell: bash