name: Say Hello World
on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: assign to maintainer
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: >-
          curl -H
          "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          -X POST
          -d '{"assignees": ["abikouo"]}'
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees