name: Say Hello World
on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Going to push to this URL
        run: |
          echo 'https://api.github.com/repos/${PR_REPOSITORY}/issues/${PR_NUMBER}/assignees'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_REPOSITORY: ${{ github.repository }}