---
name: k8s_kind

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Kubernetes cluster with local registry
    env:
      registry_user: ansible
      register_pass: "test123!"
    steps:
      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
        shell: bash

      - name: Create credentials for cluster authentication
        run: echo "${{ env.register_pass }}" | htpasswd -i -c htpasswd ${{ env.registry_user }}
        shell: bash

      - name: Create Kubernetes cluster without local registry
        uses: helm/kind-action@v1.4.0
        with:
          install_only: true  

      - name: Create registry container
        run: >-
          docker run -d
          -p 5001:5000
          --restart=always
          --name "kind-registry"
          -v "${PWD}:/auth"
          -e "REGISTRY_AUTH=htpasswd"
          -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
          -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
          registry:2
        shell: bash

      - name: Try login to OCI registry
        run: >-
          helm registry login 
          -u ${{ env.registry_user }}
          -p '${{ env.register_pass }}'
          --insecure 
          localhost:5001
        shell: bash
  
      # - name: Package helm chart
      #   command: >-
      #     {{ helm_binary_path }} package
      #     "{{ role_path }}/files/python-chart"
      #     --destination {{ _tmpfile.path }}
  
      # - name: Helm push chart to the registry
      #   command: >-
      #     {{ helm_binary_path }} push
      #     {{ _tmpfile.path }}/python-app-0.1.0.tgz
      #     oci://localhost:{{ registry_port }}/helm-charts
  
      # - name: Show chart from registry
      #   command: >-
      #     {{ helm_binary_path }} show all oci://localhost:{{ registry_port }}/helm-charts/python-app
  
      # - name: Logout from registry
      #   command: >-
      #     {{ helm_binary_path }} registry logout localhost:{{ registry_port }}
  