---
name: k8s_kind

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Kubernetes cluster with local registry
    steps:
      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh\
          helm version
        shell: bash

      - name: Create kubernetes cluster with local registry
        uses: abikouo/github_actions/.github/actions/ansible_k8s_cluster@kind_with_private_registry
        with:
          configure_registry: true