---
name: migrate_modules

on:
  workflow_dispatch:
    inputs:
      token:
        description: The Github token to use to create/list pull request
        required: true
      module:
        description: The module to migrate
        required: true
      src:
        description: |
          The Github repository source, user must have a repository with this name.
          Please do not specify repository owner, we consider the user running this
          workflow as the owner.
        required: false
        default: 'community.aws'
      dest:
        description: |
          The Github repository destination, user must have a repository with this name.
          Please do not specify repository owner, we consider the user running this
          workflow as the owner.
        required: false
        default: "amazon.aws"
      prefix:
        description: The prefix name for branch to create for migration.
        required: false
        default: "promote"
  

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Migrate modules from community
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
      GITHUB_USERNAME: ${{ github.actor }}
      GIT_USER_NAME: ${{ github.actor }}
      GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      GIT_AUTHOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
      PY_COLORS: "1"
      promoter_path: "./promoter"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install ansible-core
        run: >
          python3 -m pip install
          https://github.com/ansible/ansible/archive/milestone.tar.gz
          --disable-pip-version-check

      # checkout el_grandiose_module_promoter
      - name: Checkout the repository el_grandiose_module_promoter
        uses: actions/checkout@v3
        with:
          repository: abikouo/el_grandiose_module_promoter
          ref: automation_1
          path: ${{ env.promoter_path }}

      # checkout source repository
      - name: Checkout the source collection
        uses: actions/checkout@v3
        with:
          repository: "${{ github.actor }}/${{ inputs.src }}"
          path: "${{ env.promoter_path }}/${{ inputs.src }}"
          fetch-depth: "0"

      # checkout destination repository
      - name: Checkout the destination collection
        uses: actions/checkout@v3
        with:
          repository: "${{ github.actor }}/${{ inputs.dest }}"
          path: "${{ env.promoter_path }}/${{ inputs.dest }}"
          fetch-depth: "0"

      # Run playbook
      - name: Run playbook to migrate modules
        run: >
          ansible-playbook ./migrate.yaml 
          -e "migrate_module_name=${{ inputs.module }}"
          -e "migration_src_path=${{ inputs.src }}"
          -e "migration_dst_path=${{ inputs.dest }}"
          -e "branch_prefix=${{ inputs.prefix }}"
          -v
        shell: bash
        working-directory: ${{ env.promoter_path }}