---
name: okd-downstream

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The Github repository to checkout
        required: true
      ref:
        description: The Github ref to checkout
        required: false
        default: main
        type: string
      command:
        description: The command to perform
        type: choice
        options:
          - test-sanity
          - test-units
          - test-integration
          - build

jobs:
  run:
    runs-on: ubuntu-latest
    name: Downstream community.okd
    env:
      collection_path: "./source"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ansible-core
        run: >
          python3 -m pip install
          https://github.com/ansible/ansible/archive/milestone.tar.gz
          --disable-pip-version-check

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: ${{ env.collection_path }}
      
      - name: Perform the action
        run: make downstream-${{ inputs.command }}
        shell: bash
        working-directory: ${{ env.collection_path }}
        env:
          DOWNSTREAM_BUILD_PYTHON: python3.10