---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    if: "{{ (github.event.pull_request.merged == true) and contains(github.event.pull_request.labels.*.name, 'ok-to-tag') }}"
    steps:
     - name: Display message
       run: echo 'The pull request has been closed and contains expected tag'
       shell: bash
