---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request:
    types: [closed]
    branches:
      - stable-*

jobs:
  tag:
    permissions:
      contents: write
    uses: abikouo/github_actions/.github/workflows/create_tag_from_galaxy.yml@release_v1