---
name: Release
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: a new release has been published
        run: echo 'a new release has been published'
        shell: bash