---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed
    branches:
      - stable-*

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Display context
        run: echo "Pull request status -> $PR_STATE"
        env:
          PR_STATE: ${{ github.event.pull_request.merged }}