---
name: Code review - Size pull requests
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: The token used for commenting/labelling on pull requests.
        required: true
jobs:
  pull-request-size:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: abikouo/gha_testing/.github/actions/size_pull_request@main
        with:
          path: "."
          github_token: ${{ secrets.GH_TOKEN }}