name: pull_request
concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request_target:

jobs:
  create:
    permissions:
      contents: write
      pull-requests: write
    env:
      source_dir: "./source"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.source_dir }}
          fetch-depth: "0"

      - name: create new file
        run: echo 'This has been release for 1.0.0' > release_note.txt
        working-directory: ${{ env.source_dir }}

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.source_dir }}
          commit-message: "Release 1.0.0"
          base: "stable-1.0"
          branch: "prepare_release_100"
          title: "Prepare release 1.0.0"
          body: "Release 1.0.0"