---
name: push commit

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The target branch
        required: true
        type: string
      value:
        description: The value to commit
        required: true
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.branch }}
          fetch-depth: "0"

      - name: Update file content
        run: echo "${{ inputs.value }}" >> release.txt
        shell: bash

      - name: Commit and push changes
        run: |
          git add release.txt
          git -c user.name="$GIT_USER_NAME" -c user.email="$GIT_USER_EMAIL" commit -m "Pushing update for branch ${{ inputs.value }}" --author="$GIT_AUTHOR"
          git push origin ${{ inputs.branch }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USER_NAME: "${{ github.actor }}"
          GIT_USER_EMAIL: "${{ github.actor }}@users.noreply.github.com"
          GIT_AUTHOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
