---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  prepare:
    permissions:
      contents: write
      pull-requests: write
    uses: abikouo/github_actions/.github/workflows/release-branch.yml@release_v2