---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The release tag
        required: true
      branch:
        description: The branch to release
        required: false
        default: main

jobs:
  prepare:
    permissions:
      contents: write
      pull-requests: write
    uses: ansible-network/github_actions/.github/workflows/release-branch.yml@main
    with:
      tag: ${{ github.event.inputs.tag }}
      branch: ${{ github.event.inputs.branch }}