---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The release tag
        required: true

jobs:
  prepare:
    permissions:
      contents: write
      pull-requests: write
    uses: abikouo/github_actions/.github/workflows/release-branch.yml@release_v5
    with:
      version: ${{ github.event.inputs.tag }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}