---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  issues:
    types:
      - reopened
      - labeled
      - unlabeled
      - opened
      - edited
      - closed

jobs:
  release:
    permissions:
      contents: write
    uses: abikouo/github_actions/.github/workflows/release.yml@release_v1