---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed
    branches:
      - stable-*

jobs:
  tag:
    permissions:
      contents: write
      pull-requests: write
    uses: abikouo/github_actions/.github/workflows/release-tag.yml@release_v1