---
name: Release

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: The release base branch
        required: true

jobs:
  prepare:
    permissions:
      contents: write
      pull-requests: write
    uses: ansible-network/github_actions/.github/workflows/release-branch.yml@main
    with:
      release_branch: ${{ github.event.inputs.release_branch }}