---
name: safe-to-test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test_var_setting:
    runs-on: ubuntu-latest
    name: set variable
    steps:
      - name: set variable when command separated
        id: test1
        run: |
          set -eux
          RES=""
          for var in $(echo $COMPOSE | tr ' ' '\n'); do
            RES="-c ${var} ${RES}"
          done
          echo "test=${RES}" >> $GITHUB_OUTPUT
        shell: bash
        env:
          COMPOSE: 'requirements.txt test-requirements.txt'

      - name: set variable when command separated
        id: test2
        run: |
          set -eux
          RES=""
          for var in $(echo $COMPOSE | tr ' ' '\n'); do
            RES="-c ${var} ${RES}"
          done
          echo "test=${RES}" >> $GITHUB_OUTPUT
        shell: bash
        env:
          COMPOSE: |
            requirements.txt
            test-requirements.txt
      
      - name: read environment variable from test1
        run: echo "${{ steps.test1.outputs.test }}"
        shell: bash
      
      - name: read environment variable from test2
        run: echo "${{ steps.test2.outputs.test }}"
        shell: bash