---
name: safe-to-test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - '*'

jobs:
  safe-to-test:
    uses: abikouo/gha_testing/.github/workflows/safe-to-test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   