---
name: safer

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      repository:
        description: repository
        required: true
      login:
        description: login
        required: true
      id:
        description: id
        required: true

jobs:
  safe-to-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_API_HEADERS: >-
        -H "Accept: application/vnd.github+json"
        -H "X-GitHub-Api-Version: 2022-11-28"
      GH_COLLABORATORS_PERMISSION: >-
        [
          "pull",
          "triage",
          "push",
          "maintain",
          "admin"
        ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}

      - name: Get user permission for repository
        id: read-permission
        run: |
          PERM=$(gh api --jq .permission -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $GH_API_URL)
          echo "user_permission=$PERM" >> $GITHUB_OUTPUT
        env:
          GH_API_URL: "/repos/${{ inputs.repository }}/collaborators/${{ inputs.login }}/permission"

      - name: Get pull request labels
        id: read-label
        run: |
          SAFE_LABEL=$(gh api --jq '.[] | select(.name == "safe to test") | .name' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" $GH_API_URL)
          echo "safe_label=$SAFE_LABEL" >> $GITHUB_OUTPUT
        env:
          GH_API_URL: /repos/${{ inputs.repository }}/issues/${{ inputs.id }}/labels

      - name: Display values
        run: |
          echo "permission = ${{steps.read-permission.outputs.user_permission}} - label = ${{steps.read-label.outputs.safe_label}}"

      - name: Display collaborator message
        run: echo "${{ inputs.login }} is a collaborator for this repository"
        shell: bash
        if: ${{ contains(fromJSON(env.GH_COLLABORATORS_PERMISSION), steps.read-permission.outputs.user_permission) }}