name: tagging

on:
  workflow_call:
    inputs:
      branch_name:
        description: The branch name to create tag from.
        type: string
        default: ${{ github.base_ref }}
      release_publish:
        default: true
        description: Publish a new github release.
        type: boolean
      release_prefix:
        default: "Release"
        description: Prefix name of the release to create.
        type: string
    secrets:
      # due to https://github.com/ad-m/github-push-action/issues/32 we are not using default GITHUB_TOKEN
      gh_token:
        required: true

jobs:
  push:
    if: ${{ github.event.pull_request.merged == true }} and ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-tag') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.gh_token }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install python libraries
        run: pip3 install yq pygithub
        shell: bash

      - name: extract tag name from 'galaxy.yml'
        id: read-tag
        run: echo "release_tag=$(yq -r '.version' 'galaxy.yml')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Pull Request from Release branch to default branch
        uses: ansible-network/github_actions/.github/actions/create_pullrequest@main
        with:
          token: ${{ secrets.gh_token }}
          repository: ${{ github.repository }}
          base_branch: ${{ steps.push-tag.outputs.default_branch }}
          head_branch: ${{ inputs.branch_name }}
          title: "Push changes for release '${{ steps.read-tag.outputs.release_tag }}' on 'main' branch"
          body: "Automatic changes for Release ${{ steps.read-tag.outputs.release_tag }} on Repository default branch"