---
name: test update versionning

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - '*'

jobs:
  build_terraform:
    runs-on: ubuntu-20.04
    env:
      source: "collection"
    steps:
      - name: checkout collection
        uses: ansible-network/github_actions/.github/actions/checkout_dependency@main
        with:
          repository: ansible-collections/cloud.terraform
          path: ${{ env.source }}
          ref: main

      - name: Build collection
        id: build
        uses: abikouo/github_actions/.github/actions/build_install_collection@build_install_v2
        with:
          source_path: ${{ env.source }}
          install_python_dependencies: "true"

      - name: Display collection final path
        run:
          echo "final collection install path => [${{ steps.build.outputs.collection_path }}]"
        shell: bash
