---
name: test update versionning

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  pr_updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: made some change to the pull request
        run: |
          echo "testing=$(date)" >> config.txt
          git add config.txt
          git -c user.name="$COMMIT_USER_NAME" -c user.email="$COMMIT_USER_EMAIL" commit -m "$COMMIT_MESSAGE" --author="$COMMIT_AUTHOR"
        shell: bash
        env:
          COMMIT_USER_NAME: ${{ github.actor }}
          COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MESSAGE: "apply galaxy.yml changes"
          COMMIT_AUTHOR: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
