---
name: changelog

on:
  workflow_dispatch:
    inputs:
      repository:
        description: repository
        required: true
      ref:
        description: The reference branch/tag/sha to checkout
        required: true
      base_ref:
        description: The base reference
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Require a changelog
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          fetch-depth: "0"

      - name: Validate changelog
        uses: abikouo/github_actions/.github/actions/ansible_validate_changelog@changelog_roles
        with:
          base_ref: ${{ inputs.base_ref }}