---
name: test update versionning

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - '*'

jobs:
  labelling:
    runs-on: ubuntu-latest
    steps:
      - name: Test even number
        run: echo 'event number -> $E_NUMBER'
        env:
          E_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        shell: bash