---
name: test update versionning

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - '*'

jobs:
  build_terraform:
    runs-on: ubuntu-20.04
    env:
      source: "collection"
    steps:
      - name: checkout collection
        uses: ansible-network/github_actions/.github/actions/checkout_dependency@main
        with:
          repository: ansible-collections/cloud.terraform
          path: ${{ env.source }}
          ref: main

      - name: Read collection metadata from galaxy.yml
        id: identify
        uses: ansible-network/github_actions/.github/actions/identify_collection@main
        with:
          source_path: ${{ env.source }}

      - name: Build collection
        id: build
        uses: abikouo/github_actions/.github/actions/build_install_collection@build_install_v2
        with:
          source_path: ${{ env.source }}
          install_python_dependencies: "true"
          collection_path: ${{ steps.identify.outputs.collection_path }}
          tar_file: ${{ steps.identify.outputs.tar_file }}

      - name: Display collection final path
        run:
          echo "Final collection install path => [${{ steps.build.outputs.collection_path }}]"
        shell: bash
