name: Release

on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Create release branch on Github repository
        id: create-branch
        run: |
          git branch -r
          RELEASE_BRANCH="stable-0"
          BRANCH_EXISTS="1"
          git checkout $RELEASE_BRANCH || git checkout main && git checkout -b $RELEASE_BRANCH & BRANCH_EXISTS="0"
          if [ "$BRANCH_EXISTS" == "1" ]; then
            echo "The branch ${RELEASE_BRANCH} exists"
            exit 0
          fi
        shell: bash