---
name: Update linters Job
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ['Prepare integration tests']
    types:
      - completed

jobs:
  update-job-status-pending:
    uses: abikouo/cloud-content-ci-automation/.github/workflows/update-job-status.yml@aws_oidc_1
    with:
      job_name: 'run-tests'

  download-refs:
    needs: update-job-status-pending
    uses: abikouo/cloud-content-ci-automation/.github/workflows/download-refs.yml@aws_oidc_1

  ansible-test-splitter:
    name: ansible test splitter
    needs: download-refs
    permissions:
      pull-requests: read
    env:
      base_ref: ${{ needs.download-refs.outputs.content }}
      amazon_dir: "./amazon_aws"
      community_dir: "./community_aws"
    outputs:
      jobs: ${{ steps.compute.outputs.jobs }}
      targets: ${{ steps.compute.outputs.targets }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout amazon.aws collection
        uses: actions/checkout@v4
        with:
          repository: ansible-collections/amazon.aws
          path: "${{ env.amazon_dir }}"

      - name: Checkout community.aws collection
        uses: actions/checkout@v4
        with:
          repository: ansible-collections/community.aws
          path: "${{ env.community_dir }}"

      - name: Add remote repository
        run: |
          cd ./amazon_aws
          git remote add tremble https://github.com/tremble/amazon.aws.git
          git fetch tremble
          git checkout tremble/feature/s3-bucket-logging

      - name: list changes for pull request
        id: compute
        uses: abikouo/cloud-content-ci-automation/.github/actions/ansible_test_splitter@aws_oidc_1
        with:
          collections_to_test: "${{ env.amazon_dir}}, ${{ env.community_dir }}"
          total_jobs: 4
          base_ref: ${{ env.base_ref }}

  run-tests:
    needs: ansible-test-splitter
    permissions:
      pull-requests: read
    env:
      amazon_dir: "./amazon_aws"
      community_dir: "./community_aws"
      ansible_test_splitter_targets: "${{ needs.ansible-test-splitter.outputs.targets }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job-id: ${{ fromJson(needs.ansible-test-splitter.outputs.jobs) }}
    name: "integration-${{ matrix.job-id }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read job targets
        id: read-targets
        uses: abikouo/cloud-content-ci-automation/.github/actions/ansible_read_targets@aws_oidc_1
        with:
          job_id: "${{ matrix.job-id }}"
          all_targets: "${{ env.ansible_test_splitter_targets }}"

      - name: Display ansible-test targets
        run: echo "Job targets => ${TEST_TARGETS}"
        env:
          TEST_TARGETS: "${{ steps.read-targets.outputs.job_targets }}"

  update-job-status-result:
    needs: run-tests
    uses: abikouo/cloud-content-ci-automation/.github/workflows/update-job-status.yml@aws_oidc_1
    with:
      job_name: 'run-tests'
      job_result: '${{ needs.run-tests.result }}'