---
name: test update versionning

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - '*'

jobs:
  changelog:
    uses: abikouo/github_actions/.github/workflows/changelog.yml@test_gha_cloud
   