---
name: splitter

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      repository:
        description: repository
        required: true
      ref:
        description: The reference branch/tag/sha to checkout
        required: true
      base_ref:
        description: The base reference
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: ansible test splitter
    env:
      source_dir: "source"
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          fetch-depth: "0"
          path: ${{ env.source_dir }}

      - name: List changes for pull request
        id: splitter
        uses: abikouo/github_actions/.github/actions/ansible_test_splitter@splitter_for_roles
        with:
          collections_to_test: ${{ env.source_dir }}
          total_jobs: 2
          base_ref: main

      - name: Display targets
        run: echo "test_targets=${{ steps.splitter.outputs.test_targets }}"
        shell: bash