---
name: update collection variables

concurrency:
  group: '${{ github.workflow }} @ ${{ github.sha }}'
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - 'stable-*'
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  update-variables:
    uses: ansible-network/github_actions/.github/workflows/update_aws_variables.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}